import type {
  ActivityItem,
  AppNotification,
  ComponentCondition,
  Game,
  GameRules,
  PlayTable,
  ReportDay,
  Staff,
  StoreSettings,
  Transaction,
} from "./types";

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60000).toISOString();
const vietnamDateFormatter = new Intl.DateTimeFormat("en-US", {
  timeZone: "Asia/Ho_Chi_Minh",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
  weekday: "short",
});

function vietnamCalendarDay(date: Date) {
  const parts = Object.fromEntries(
    vietnamDateFormatter.formatToParts(date).map((part) => [part.type, part.value]),
  );

  return {
    date: `${parts.year}-${parts.month}-${parts.day}`,
    weekend: parts.weekday === "Sat" || parts.weekday === "Sun",
  };
}

const comp = (
  name: string,
  qty: number,
  condition: ComponentCondition = "ok",
  missingQty = 0,
  note?: string,
) => ({
  id: `${name}-${qty}`.replace(/\s+/g, "-").toLowerCase(),
  name,
  qty,
  condition,
  missingQty,
  note,
});

const GAME_RULES: Record<string, GameRules> = {
  g1: {
    objective:
      "Xây dựng khu định cư, thành phố và đường để trở thành người đầu tiên đạt 10 điểm chiến thắng.",
    setup: [
      "Ghép bản đồ, đặt số lên các ô địa hình và để quân cướp ở sa mạc.",
      "Mỗi người lần lượt đặt 2 khu định cư cùng 2 con đường và nhận tài nguyên từ vị trí thứ hai.",
    ],
    gameplay: [
      "Đầu lượt, gieo hai xúc xắc; các ô có số tương ứng sản xuất tài nguyên cho người có công trình giáp ô đó.",
      "Nếu ra 7, người giữ quá 7 lá bỏ một nửa, sau đó người chơi di chuyển quân cướp và lấy ngẫu nhiên một lá từ đối thủ phù hợp.",
      "Trong lượt, người chơi có thể trao đổi tài nguyên rồi xây đường, khu định cư, thành phố hoặc mua thẻ phát triển.",
    ],
    ending: "Người đầu tiên có ít nhất 10 điểm chiến thắng trong lượt của mình thắng game.",
    notes: ["Áp dụng luật Catan bản cơ bản, không bao gồm bản mở rộng."],
  },
  g2: {
    objective: "Ghi nhiều điểm nhất bằng cách xây các tuyến đường sắt và hoàn thành vé hành trình.",
    setup: [
      "Mỗi người nhận toa tàu, quân tính điểm, 4 thẻ toa tàu và các vé hành trình ban đầu.",
      "Mỗi người giữ số vé tối thiểu theo luật rồi trả các vé không chọn về hộp.",
    ],
    gameplay: [
      "Mỗi lượt chọn một việc: rút thẻ toa tàu, dùng bộ thẻ cùng màu để chiếm một tuyến, hoặc rút thêm vé hành trình.",
      "Chiếm tuyến sẽ ghi điểm theo độ dài; vé hành trình yêu cầu nối được hai thành phố ghi trên vé.",
      "Tuyến đã bị chiếm thường không thể được người khác sử dụng, trừ các tuyến đôi khi đủ số người chơi.",
    ],
    ending:
      "Khi một người còn 2 toa tàu trở xuống, mọi người chơi thêm một lượt; cộng điểm tuyến và vé, người nhiều điểm nhất thắng.",
  },
  g3: {
    objective:
      "Trở thành người đầu tiên đánh hết bài trên tay và ghi điểm từ bài còn lại của đối thủ.",
    setup: ["Chia mỗi người 7 lá, đặt phần còn lại thành chồng rút và lật một lá mở đầu chồng bỏ."],
    gameplay: [
      "Đến lượt, đánh một lá cùng màu, cùng số hoặc cùng biểu tượng với lá trên cùng; cũng có thể dùng lá Wild phù hợp.",
      "Nếu không đánh được, rút một lá và có thể đánh ngay nếu lá đó hợp lệ.",
      "Khi còn một lá, phải hô UNO; nếu bị phát hiện trước lượt kế tiếp thì phải rút phạt.",
      "Các lá hành động đổi chiều, bỏ lượt, bắt rút hoặc đổi màu theo biểu tượng trên lá.",
    ],
    ending:
      "Ván kết thúc khi một người hết bài; có thể chơi một ván thắng ngay hoặc cộng điểm qua nhiều ván theo luật cơ bản.",
  },
  g4: {
    objective: "Tránh rút phải Exploding Kitten và trở thành người sống sót cuối cùng.",
    setup: [
      "Mỗi người nhận 1 lá Defuse và 7 lá khác.",
      "Trộn số lá Exploding Kitten ít hơn số người chơi một lá cùng các lá Defuse còn lại vào chồng rút.",
    ],
    gameplay: [
      "Trong lượt, người chơi có thể đánh không giới hạn lá hành động rồi phải rút một lá để kết thúc lượt.",
      "Nếu rút Exploding Kitten, người chơi phải dùng Defuse và đặt lại lá nổ vào chồng rút; nếu không có Defuse thì bị loại.",
      "Các lá hành động cho phép bỏ lượt, xem trước, xáo bài, yêu cầu người khác hoặc lấy bài theo hiệu ứng ghi trên lá.",
    ],
    ending: "Người duy nhất chưa bị loại thắng game.",
  },
  g5: {
    objective:
      "Ghi điểm bằng cách đưa ra gợi ý vừa đủ để một số, nhưng không phải tất cả, người chơi nhận ra thẻ tranh của mình.",
    setup: [
      "Mỗi người nhận 6 thẻ tranh, một quân tính điểm và bộ thẻ hoặc token bình chọn tương ứng.",
      "Chọn một người làm người kể chuyện đầu tiên.",
    ],
    gameplay: [
      "Người kể chuyện chọn bí mật một thẻ, đưa ra một câu, từ hoặc âm thanh gợi ý rồi đặt úp thẻ xuống.",
      "Mỗi người khác chọn một thẻ trên tay phù hợp với gợi ý; người kể chuyện trộn tất cả rồi lật ngửa.",
      "Những người không kể chuyện bí mật bình chọn thẻ của người kể chuyện và sau đó tính điểm.",
      "Nếu tất cả hoặc không ai đoán đúng, người kể chuyện không có điểm và những người khác được 2 điểm; trường hợp còn lại người kể chuyện cùng người đoán đúng được 3 điểm. Mỗi người còn nhận thêm 1 điểm cho mỗi phiếu vào thẻ của mình.",
      "Mọi người rút lại đủ 6 thẻ và vai trò kể chuyện chuyển sang người kế tiếp.",
    ],
    ending: "Khi chồng thẻ hết, người có tổng điểm cao nhất thắng.",
  },
  g6: {
    objective:
      "Thu thập đá quý để mua thẻ phát triển, thu hút quý tộc và đạt nhiều điểm danh vọng nhất.",
    setup: [
      "Xếp ba cấp thẻ phát triển thành ba hàng, lật 4 thẻ mỗi cấp và bày token đá quý theo số người.",
      "Lật số thẻ quý tộc bằng số người chơi cộng một.",
    ],
    gameplay: [
      "Mỗi lượt chọn một việc: lấy 3 token khác màu, lấy 2 token cùng màu khi còn đủ, giữ một thẻ kèm token vàng, hoặc mua một thẻ.",
      "Thẻ đã mua tạo giảm giá vĩnh viễn cho các lần mua sau và có thể cung cấp điểm danh vọng.",
      "Cuối lượt, nếu đáp ứng yêu cầu của một quý tộc, người chơi nhận quý tộc đó; thông thường chỉ nhận tối đa một quý tộc mỗi lượt.",
      "Người chơi không được giữ quá 10 token vào cuối lượt.",
    ],
    ending:
      "Khi có người đạt ít nhất 15 điểm, hoàn tất vòng để mọi người có số lượt bằng nhau; người nhiều điểm nhất thắng.",
  },
  g7: {
    objective: "Đội mình đoán hết các từ khóa của đội trước đối thủ mà không chọn phải sát thủ.",
    setup: [
      "Chia người chơi thành hai đội, mỗi đội chọn một đội trưởng gợi ý.",
      "Bày 25 thẻ từ thành lưới 5 × 5; hai đội trưởng xem chung một thẻ đáp án bí mật.",
    ],
    gameplay: [
      "Đội trưởng nói đúng một từ gợi ý và một con số cho biết có bao nhiêu từ liên quan.",
      "Đồng đội thảo luận và chọn từng thẻ; đoán đúng màu đội mình có thể tiếp tục, còn đoán nhầm thường kết thúc lượt.",
      "Đội trưởng không được đưa thêm tín hiệu ngoài gợi ý hợp lệ.",
    ],
    ending:
      "Đội lật hết các đặc vụ của mình trước sẽ thắng; đội chọn phải thẻ sát thủ thua ngay lập tức.",
  },
  g8: {
    objective:
      "Phe Thiện hoàn thành 3 nhiệm vụ và bảo vệ Merlin; phe Ác làm thất bại 3 nhiệm vụ hoặc ám sát đúng Merlin.",
    setup: [
      "Chọn bộ nhân vật phù hợp số người, bí mật phát một vai cho mỗi người rồi thực hiện bước nhận biết phe theo hướng dẫn vai.",
      "Đặt bảng nhiệm vụ, token biểu quyết và token kết quả nhiệm vụ ở giữa bàn.",
    ],
    gameplay: [
      "Thủ lĩnh đề xuất một đội đi làm nhiệm vụ; tất cả cùng biểu quyết chấp thuận hoặc từ chối đội hình.",
      "Nếu được chấp thuận, thành viên nhiệm vụ bí mật chọn thành công hoặc thất bại; người phe Thiện bắt buộc chọn thành công.",
      "Nhiệm vụ thường thất bại khi có ít nhất một phiếu thất bại; ở bàn 7 người trở lên, nhiệm vụ thứ tư cần ít nhất hai phiếu thất bại.",
      "Quyền thủ lĩnh chuyển vòng và quá nhiều đội hình liên tiếp bị từ chối sẽ giúp phe Ác thắng.",
    ],
    ending:
      "Phe Ác thắng khi có 3 nhiệm vụ thất bại. Nếu phe Thiện hoàn thành 3 nhiệm vụ, Sát thủ được đoán Merlin; đoán đúng thì phe Ác thắng, sai thì phe Thiện thắng.",
  },
  g9: {
    objective: "Làm các đối thủ phá sản bằng cách sở hữu bất động sản, xây nhà và thu tiền thuê.",
    setup: [
      "Mỗi người chọn quân cờ và nhận số tiền ban đầu theo bộ game.",
      "Đặt thẻ tài sản, Chance, Community Chest, nhà và khách sạn cạnh bàn cờ.",
    ],
    gameplay: [
      "Trong lượt, gieo xúc xắc, di chuyển và xử lý ô dừng: mua tài sản, trả tiền thuê, rút thẻ, nộp thuế hoặc vào tù.",
      "Nếu không mua tài sản chưa có chủ, ngân hàng đưa tài sản ra đấu giá.",
      "Sở hữu đủ một nhóm màu cho phép xây nhà và khách sạn đồng đều để tăng tiền thuê.",
      "Người chơi có thể giao dịch, thế chấp tài sản và phải xử lý phá sản nếu không trả được nợ.",
    ],
    ending: "Người chơi cuối cùng chưa phá sản thắng game.",
    notes: ["Dùng luật Monopoly tiêu chuẩn, không áp dụng tiền thưởng tại ô Free Parking."],
  },
  g10: {
    objective:
      "Loại hết ảnh hưởng của đối thủ và trở thành người cuối cùng còn ít nhất một thẻ nhân vật úp.",
    setup: [
      "Mỗi người nhận 2 đồng xu và 2 thẻ nhân vật úp; phần thẻ còn lại tạo thành Court deck.",
    ],
    gameplay: [
      "Mỗi lượt thực hiện một hành động chung hoặc tuyên bố hành động của một nhân vật, kể cả khi không thật sự giữ nhân vật đó.",
      "Người khác có thể thách thức tuyên bố hoặc dùng nhân vật phù hợp để chặn hành động.",
      "Người thua thách thức phải lật một ảnh hưởng; thẻ đã lật không còn khả năng sử dụng.",
      "Có từ 7 xu phải Coup; Coup tốn 7 xu và buộc mục tiêu mất một ảnh hưởng. Người có từ 10 xu bắt buộc Coup.",
    ],
    ending: "Người cuối cùng còn ảnh hưởng chưa bị lật thắng game.",
  },
  g11: {
    objective:
      "Ghi nhiều điểm nhất bằng cách hoàn thiện các hàng gạch trên bức tường cá nhân và hạn chế gạch rơi xuống sàn.",
    setup: [
      "Mỗi người nhận một bảng cá nhân và đặt quân tính điểm ở 0.",
      "Bày số đĩa nhà máy theo số người, đặt ngẫu nhiên 4 viên gạch lên mỗi đĩa.",
    ],
    gameplay: [
      "Trong lượt, lấy tất cả gạch cùng màu từ một đĩa nhà máy hoặc khu vực giữa bàn; gạch còn lại trên đĩa được đẩy vào giữa.",
      "Đặt gạch đã lấy vào một hàng mẫu hợp lệ; gạch không đặt được phải xuống hàng sàn và gây trừ điểm.",
      "Khi hết gạch ở các nhà máy và giữa bàn, chuyển một gạch từ mỗi hàng mẫu hoàn chỉnh sang tường rồi tính điểm theo các gạch liền kề.",
      "Chuẩn bị vòng mới và tiếp tục chơi.",
    ],
    ending:
      "Game kết thúc sau vòng có người hoàn thành một hàng ngang trên tường; cộng điểm thưởng hàng, cột và bộ màu, người nhiều điểm nhất thắng.",
  },
  g12: {
    objective: "Tạo các bộ món ăn có giá trị cao qua ba vòng draft bài và đạt tổng điểm lớn nhất.",
    setup: [
      "Trộn bộ bài và chia số lá theo số người; giữ kín bài trên tay.",
      "Mỗi vòng dùng một tay bài mới từ chồng bài chung.",
    ],
    gameplay: [
      "Mọi người đồng thời chọn một lá, đặt úp, cùng lật lên rồi chuyền toàn bộ bài còn lại sang người bên cạnh.",
      "Tiếp tục chọn và chuyền đến khi hết bài trên tay.",
      "Cuối vòng, tính điểm theo từng loại món: sashimi, tempura, dumpling, maki, nigiri và wasabi theo biểu tượng trên lá.",
      "Giữ lại pudding đến cuối game; bỏ các lá khác rồi chia bài cho vòng tiếp theo.",
    ],
    ending: "Sau 3 vòng, tính thêm điểm pudding; người có tổng điểm cao nhất thắng.",
  },
};

export const GAME_CATEGORIES = [
  "Chiến thuật",
  "Gia đình",
  "Party",
  "Suy luận",
  "Sáng tạo",
  "Kinh tế",
];

const gamesWithoutRules: Game[] = [
  {
    id: "g1",
    code: "BG-001",
    name: "Catan",
    category: "Chiến thuật",
    minPlayers: 3,
    maxPlayers: 4,
    duration: 75,
    difficulty: "Trung bình",
    status: "in_use",
    location: "Kệ A - Ngăn 1",
    description:
      "Trò chơi xây dựng và trao đổi tài nguyên trên hòn đảo Catan, phù hợp nhóm bạn thích thương lượng.",
    age: 10,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: false,
    emoji: "🏝️",
    tone: 1,
    components: [
      comp("Ô địa hình", 19),
      comp("Mảnh khung biển", 6),
      comp("Thẻ số", 18),
      comp("Thẻ tài nguyên", 95),
      comp("Thẻ phát triển", 25),
      comp("Quân cờ 4 màu", 4),
      comp("Xúc xắc", 2),
      comp("Quân cướp", 1),
    ],
    history: [
      { id: "h1", type: "deliver", label: "Giao cho Bàn 03", staff: "Trần Minh Khoa", at: iso(48) },
      { id: "h2", type: "return", label: "Nhận lại từ Bàn 07", staff: "Lê Thu Hà", at: iso(300) },
    ],
    incidents: [],
    notes: "Hộp đựng thẻ đã được thay mới tháng trước.",
    usage30d: 42,
  },
  {
    id: "g2",
    code: "BG-002",
    name: "Ticket to Ride",
    category: "Gia đình",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 60,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 2",
    description:
      "Nối các tuyến đường sắt xuyên quốc gia, luật đơn giản và dễ hướng dẫn cho khách mới.",
    age: 8,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🚂",
    tone: 2,
    components: [
      comp("Bàn cờ", 1),
      comp("Toa tàu nhựa", 240),
      comp("Thẻ toa tàu", 110),
      comp("Thẻ tuyến đường", 30),
      comp("Bảng điểm", 5),
    ],
    history: [
      { id: "h3", type: "return", label: "Nhận lại từ Bàn 02", staff: "Lê Thu Hà", at: iso(180) },
    ],
    incidents: [],
    notes: "",
    usage30d: 51,
  },
  {
    id: "g3",
    code: "BG-003",
    name: "Uno",
    category: "Party",
    minPlayers: 2,
    maxPlayers: 10,
    duration: 20,
    difficulty: "Dễ",
    status: "available",
    location: "Kệ B - Ngăn 1",
    description: "Game bài nhanh gọn, phù hợp nhóm đông và khách chờ bàn.",
    age: 6,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🃏",
    tone: 5,
    components: [comp("Bộ bài", 112), comp("Hướng dẫn", 1)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 88,
  },
  {
    id: "g4",
    code: "BG-004",
    name: "Exploding Kittens",
    category: "Party",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 15,
    difficulty: "Dễ",
    status: "pending_check",
    location: "Kệ B - Ngăn 2",
    description: "Game bài hài hước, vòng chơi ngắn, dễ tạo không khí sôi động.",
    age: 7,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🐱",
    tone: 3,
    components: [comp("Thẻ bài", 56), comp("Hộp đựng", 1), comp("Hướng dẫn", 1)],
    history: [
      { id: "h4", type: "return", label: "Nhận lại từ Bàn 05", staff: "Phạm Gia Bảo", at: iso(25) },
    ],
    incidents: [],
    notes: "Cần kiểm tra lại số lượng thẻ sau ca tối.",
    usage30d: 73,
  },
  {
    id: "g5",
    code: "BG-005",
    name: "Dixit",
    category: "Sáng tạo",
    minPlayers: 3,
    maxPlayers: 6,
    duration: 30,
    difficulty: "Dễ",
    status: "missing_parts",
    location: "Kệ C - Ngăn 1",
    description: "Game kể chuyện bằng tranh minh họa, nhẹ nhàng và phù hợp nhóm bạn hoặc cặp đôi.",
    age: 8,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🎨",
    tone: 4,
    components: [
      comp("Thẻ tranh", 84, "missing", 3, "Thiếu 3 thẻ sau ca chiều"),
      comp("Thỏ gỗ", 12),
      comp("Thẻ bình chọn", 36),
      comp("Bàn điểm", 1),
    ],
    history: [],
    incidents: [
      {
        id: "i1",
        level: "medium",
        title: "Thiếu 3 thẻ tranh",
        at: iso(200),
        staff: "Phạm Gia Bảo",
        resolved: false,
        kind: "components",
        details: "Thẻ tranh: thiếu 3/84. Thiếu 3 thẻ sau ca chiều",
      },
    ],
    notes: "Đã liên hệ nhà cung cấp để bổ sung thẻ.",
    usage30d: 34,
  },
  {
    id: "g6",
    code: "BG-006",
    name: "Splendor",
    category: "Kinh tế",
    minPlayers: 2,
    maxPlayers: 4,
    duration: 40,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 3",
    description:
      "Thu thập đá quý và phát triển thương hội, luật gọn nhưng có chiều sâu chiến thuật.",
    age: 10,
    interaction: "Thấp",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "💎",
    tone: 2,
    components: [comp("Chip đá quý", 40), comp("Thẻ phát triển", 90), comp("Thẻ quý tộc", 10)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 46,
  },
  {
    id: "g7",
    code: "BG-007",
    name: "Codenames",
    category: "Suy luận",
    minPlayers: 4,
    maxPlayers: 8,
    duration: 25,
    difficulty: "Dễ",
    status: "in_use",
    location: "Kệ C - Ngăn 2",
    description: "Game đoán từ theo đội, rất hợp nhóm đông và các buổi team building.",
    age: 12,
    interaction: "Cao",
    mode: "Hợp tác",
    beginnerFriendly: true,
    emoji: "🕵️",
    tone: 3,
    components: [comp("Thẻ từ khóa", 200), comp("Thẻ điệp viên", 40), comp("Khung gợi ý", 1)],
    history: [
      { id: "h5", type: "deliver", label: "Giao cho Bàn 06", staff: "Nguyễn Hải Yến", at: iso(35) },
    ],
    incidents: [],
    notes: "",
    usage30d: 64,
  },
  {
    id: "g8",
    code: "BG-008",
    name: "Avalon",
    category: "Suy luận",
    minPlayers: 5,
    maxPlayers: 10,
    duration: 45,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ C - Ngăn 3",
    description: "Game tìm nội gián theo phe, tạo nhiều tình huống tranh luận thú vị.",
    age: 12,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: false,
    emoji: "🛡️",
    tone: 1,
    components: [comp("Thẻ nhân vật", 14), comp("Thẻ nhiệm vụ", 10), comp("Bảng nhiệm vụ", 1)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 39,
  },
  {
    id: "g9",
    code: "BG-009",
    name: "Monopoly",
    category: "Kinh tế",
    minPlayers: 2,
    maxPlayers: 6,
    duration: 120,
    difficulty: "Trung bình",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game mua bán bất động sản kinh điển, thời lượng dài phù hợp nhóm chơi thong thả.",
    age: 8,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🏘️",
    tone: 4,
    components: [
      comp("Bàn cờ", 1, "damaged", 0, "Bản lề gấp bị rách"),
      comp("Tiền giấy", 200),
      comp("Thẻ tài sản", 28),
      comp("Quân cờ", 8),
      comp("Xúc xắc", 2),
    ],
    history: [],
    incidents: [
      {
        id: "i2",
        level: "high",
        title: "Bàn cờ bị hư hỏng",
        at: iso(1500),
        staff: "Đỗ Quang Huy",
        resolved: false,
        kind: "components",
        details: "Bàn cờ: Bản lề gấp bị rách",
      },
    ],
    notes: "Đang chờ ép lại bản lề bàn cờ.",
    usage30d: 12,
  },
  {
    id: "g10",
    code: "BG-010",
    name: "Coup",
    category: "Suy luận",
    minPlayers: 2,
    maxPlayers: 6,
    duration: 20,
    difficulty: "Dễ",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game bluff ngắn, luật đơn giản và dễ chơi nhiều ván liên tiếp.",
    age: 10,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🎭",
    tone: 5,
    components: [
      comp("Thẻ nhân vật", 15, "damaged", 0, "Một số thẻ bị cong góc"),
      comp("Đồng xu", 50),
    ],
    history: [],
    incidents: [
      {
        id: "i3",
        level: "low",
        title: "Thẻ nhân vật bị hư hỏng",
        at: iso(900),
        staff: "Lê Thu Hà",
        resolved: false,
        kind: "components",
        details: "Thẻ nhân vật: Một số thẻ bị cong góc",
      },
    ],
    notes: "",
    usage30d: 55,
  },
  {
    id: "g11",
    code: "BG-011",
    name: "Azul",
    category: "Chiến thuật",
    minPlayers: 2,
    maxPlayers: 4,
    duration: 40,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 4",
    description: "Xếp gạch men theo mẫu, thành phần đẹp mắt và rất được khách nữ yêu thích.",
    age: 8,
    interaction: "Thấp",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🧩",
    tone: 2,
    components: [comp("Viên gạch men", 100), comp("Bảng cá nhân", 4), comp("Đĩa nhà máy", 9)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 47,
  },
  {
    id: "g12",
    code: "BG-012",
    name: "Sushi Go",
    category: "Gia đình",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 20,
    difficulty: "Dễ",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game bài chọn và chuyền bài, vòng chơi ngắn và dễ tiếp cận cho trẻ em.",
    age: 6,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🍣",
    tone: 3,
    components: [
      comp("Thẻ món ăn", 108, "missing", 2, "Thiếu 2 thẻ sashimi"),
      comp("Hộp thiếc", 1),
    ],
    history: [],
    incidents: [
      {
        id: "i4",
        level: "medium",
        title: "Thiếu 2 thẻ sashimi",
        at: iso(2400),
        staff: "Nguyễn Hải Yến",
        resolved: false,
        kind: "components",
        details: "Thẻ món ăn: thiếu 2/108. Thiếu 2 thẻ sashimi",
      },
    ],
    notes: "",
    usage30d: 29,
  },
];

export const seedGames: Game[] = gamesWithoutRules.map((game) => ({
  ...game,
  rules: GAME_RULES[game.id],
}));

export const seedTables: PlayTable[] = [
  { id: "t1", name: "Bàn 01", seats: 4, guests: 0, status: "empty" },
  {
    id: "t2",
    name: "Bàn 02",
    seats: 4,
    guests: 3,
    status: "playing",
    gameId: "g1",
    startedAt: iso(48),
    staffId: "s3",
  },
  {
    id: "t3",
    name: "Bàn 03",
    seats: 6,
    guests: 5,
    status: "playing",
    gameId: "g7",
    startedAt: iso(35),
    staffId: "s4",
  },
  { id: "t4", name: "Bàn 04", seats: 2, guests: 0, status: "cleaning" },
  {
    id: "t5",
    name: "Bàn 05",
    seats: 6,
    guests: 6,
    status: "support",
    gameId: undefined,
    startedAt: iso(70),
    staffId: "s3",
  },
  { id: "t6", name: "Bàn 06", seats: 4, guests: 0, status: "empty" },
  {
    id: "t7",
    name: "Bàn 07",
    seats: 8,
    guests: 7,
    status: "issue",
    startedAt: iso(120),
    staffId: "s5",
  },
  { id: "t8", name: "Bàn 08", seats: 4, guests: 0, status: "empty" },
];

export const seedStaff: Staff[] = [
  {
    id: "s1",
    name: "Nguyễn Anh Tuấn",
    email: "owner@boardgameos.vn",
    role: "Chủ quán",
    shift: "Toàn thời gian",
    active: true,
    locked: false,
    actionsToday: 12,
    lastActive: iso(6),
    permissions: ["Toàn quyền"],
  },
  {
    id: "s2",
    name: "Trần Minh Khoa",
    email: "khoa@boardgameos.vn",
    role: "Quản lý",
    shift: "Ca sáng (08:00 - 16:00)",
    active: true,
    locked: false,
    actionsToday: 27,
    lastActive: iso(14),
    permissions: ["Kho game", "Bàn chơi", "Báo cáo", "Nhân viên"],
  },
  {
    id: "s3",
    name: "Lê Thu Hà",
    email: "staff@boardgameos.vn",
    role: "Nhân viên phục vụ",
    shift: "Ca chiều (14:00 - 22:00)",
    active: true,
    locked: false,
    actionsToday: 34,
    lastActive: iso(3),
    permissions: ["Giao nhận game", "Bàn chơi", "Kiểm tra linh kiện"],
  },
  {
    id: "s4",
    name: "Nguyễn Hải Yến",
    email: "yen@boardgameos.vn",
    role: "Thu ngân",
    shift: "Ca chiều (14:00 - 22:00)",
    active: true,
    locked: false,
    actionsToday: 18,
    lastActive: iso(22),
    permissions: ["Bàn chơi", "Tư vấn game"],
  },
  {
    id: "s5",
    name: "Phạm Gia Bảo",
    email: "bao@boardgameos.vn",
    role: "Nhân viên kho",
    shift: "Ca tối (17:00 - 23:00)",
    active: true,
    locked: false,
    actionsToday: 21,
    lastActive: iso(41),
    permissions: ["Kho game", "Kiểm tra linh kiện"],
  },
  {
    id: "s6",
    name: "Đỗ Quang Huy",
    email: "huy@boardgameos.vn",
    role: "Nhân viên phục vụ",
    shift: "Ca sáng (08:00 - 16:00)",
    active: false,
    locked: true,
    actionsToday: 0,
    lastActive: iso(1600),
    permissions: ["Giao nhận game"],
  },
];

export const seedTransactions: Transaction[] = [
  { id: "tx1", type: "deliver", gameId: "g7", tableId: "t3", staffId: "s4", at: iso(35) },
  { id: "tx2", type: "deliver", gameId: "g1", tableId: "t2", staffId: "s3", at: iso(48) },
  {
    id: "tx3",
    type: "return",
    gameId: "g4",
    tableId: "t5",
    staffId: "s5",
    at: iso(25),
    note: "Chờ kiểm tra linh kiện",
  },
  { id: "tx4", type: "return", gameId: "g2", tableId: "t1", staffId: "s3", at: iso(180) },
  { id: "tx5", type: "deliver", gameId: "g3", tableId: "t6", staffId: "s3", at: iso(220) },
  { id: "tx6", type: "return", gameId: "g3", tableId: "t6", staffId: "s3", at: iso(260) },
  { id: "tx7", type: "deliver", gameId: "g5", tableId: "t7", staffId: "s5", at: iso(320) },
  {
    id: "tx8",
    type: "return",
    gameId: "g5",
    tableId: "t7",
    staffId: "s5",
    at: iso(360),
    note: "Thiếu 3 thẻ tranh",
  },
  { id: "tx9", type: "deliver", gameId: "g11", tableId: "t4", staffId: "s2", at: iso(420) },
  { id: "tx10", type: "return", gameId: "g11", tableId: "t4", staffId: "s2", at: iso(470) },
];

export const seedActivities: ActivityItem[] = [
  {
    id: "a1",
    kind: "deliver",
    text: "Giao Codenames cho Bàn 03",
    at: iso(35),
    staff: "Nguyễn Hải Yến",
  },
  { id: "a2", kind: "deliver", text: "Giao Catan cho Bàn 02", at: iso(48), staff: "Lê Thu Hà" },
  {
    id: "a3",
    kind: "return",
    text: "Nhận lại Exploding Kittens từ Bàn 05",
    at: iso(25),
    staff: "Phạm Gia Bảo",
  },
  {
    id: "a4",
    kind: "missing",
    text: "Báo thiếu 3 thẻ tranh của Dixit",
    at: iso(200),
    staff: "Phạm Gia Bảo",
  },
  {
    id: "a5",
    kind: "maintenance",
    text: "Chuyển Monopoly sang bảo trì",
    at: iso(1500),
    staff: "Đỗ Quang Huy",
  },
  { id: "a6", kind: "table", text: "Bàn 07 báo cần hỗ trợ", at: iso(18), staff: "Phạm Gia Bảo" },
  {
    id: "a7",
    kind: "checklist",
    text: "Hoàn tất checklist Ticket to Ride",
    at: iso(180),
    staff: "Lê Thu Hà",
  },
  {
    id: "a8",
    kind: "return",
    text: "Nhận lại Ticket to Ride từ Bàn 02",
    at: iso(180),
    staff: "Lê Thu Hà",
  },
  {
    id: "a9",
    kind: "table",
    text: "Bàn 04 chuyển sang trạng thái đang dọn",
    at: iso(90),
    staff: "Nguyễn Hải Yến",
  },
  { id: "a10", kind: "deliver", text: "Giao Uno cho Bàn 06", at: iso(220), staff: "Lê Thu Hà" },
  { id: "a11", kind: "return", text: "Nhận lại Uno từ Bàn 06", at: iso(260), staff: "Lê Thu Hà" },
  {
    id: "a12",
    kind: "checklist",
    text: "Hoàn tất checklist Uno",
    at: iso(258),
    staff: "Lê Thu Hà",
  },
  {
    id: "a13",
    kind: "maintenance",
    text: "Chuyển Coup sang bảo trì",
    at: iso(900),
    staff: "Lê Thu Hà",
  },
  {
    id: "a14",
    kind: "missing",
    text: "Báo thiếu 2 thẻ Sushi Go",
    at: iso(2400),
    staff: "Nguyễn Hải Yến",
  },
  {
    id: "a15",
    kind: "deliver",
    text: "Giao Azul cho Bàn 04",
    at: iso(420),
    staff: "Trần Minh Khoa",
  },
  {
    id: "a16",
    kind: "return",
    text: "Nhận lại Azul từ Bàn 04",
    at: iso(470),
    staff: "Trần Minh Khoa",
  },
  {
    id: "a17",
    kind: "table",
    text: "Mở phiên chơi mới tại Bàn 03",
    at: iso(36),
    staff: "Nguyễn Hải Yến",
  },
  {
    id: "a18",
    kind: "checklist",
    text: "Hoàn tất checklist Splendor",
    at: iso(600),
    staff: "Phạm Gia Bảo",
  },
  {
    id: "a19",
    kind: "deliver",
    text: "Giao Dixit cho Bàn 07",
    at: iso(320),
    staff: "Phạm Gia Bảo",
  },
  {
    id: "a20",
    kind: "return",
    text: "Nhận lại Dixit từ Bàn 07",
    at: iso(360),
    staff: "Phạm Gia Bảo",
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n1",
    type: "Kiểm tra",
    level: "warning",
    title: "Exploding Kittens chưa được kiểm tra",
    body: "Game đã trả về từ Bàn 05 nhưng chưa hoàn tất checklist linh kiện.",
    at: iso(25),
    read: false,
    resolved: false,
    to: "/app/checklist",
  },
  {
    id: "n2",
    type: "Linh kiện",
    level: "critical",
    title: "Dixit thiếu 3 thẻ tranh",
    body: "Nhân viên Phạm Gia Bảo đã báo thiếu linh kiện trong ca chiều.",
    at: iso(200),
    read: false,
    resolved: false,
    to: "/app/games/g5",
    source: "component_inspection",
    gameId: "g5",
  },
  {
    id: "n3",
    type: "Hỗ trợ",
    level: "warning",
    title: "Bàn 07 yêu cầu hỗ trợ",
    body: "Khách cần nhân viên hướng dẫn luật chơi.",
    at: iso(18),
    read: false,
    resolved: false,
    to: "/app/tables",
  },
  {
    id: "n4",
    type: "Bảo trì",
    level: "warning",
    title: "Monopoly đang chờ bảo trì",
    body: "Bàn cờ bị rách bản lề, cần xử lý trước cuối tuần.",
    at: iso(1500),
    read: true,
    resolved: false,
    to: "/app/games/g9",
    source: "component_inspection",
    gameId: "g9",
  },
  {
    id: "n5",
    type: "Checklist",
    level: "info",
    title: "Lê Thu Hà hoàn tất checklist Ticket to Ride",
    body: "Đầy đủ linh kiện, game đã về kho.",
    at: iso(180),
    read: true,
    resolved: true,
    to: "/app/games/g2",
  },
  {
    id: "n6",
    type: "Tài khoản",
    level: "info",
    title: "Tài khoản Đỗ Quang Huy đã bị khóa",
    body: "Tài khoản tạm khóa do nghỉ ca dài ngày.",
    at: iso(1600),
    read: true,
    resolved: true,
    to: "/app/staff",
  },
];

export const seedReports: ReportDay[] = Array.from({ length: 30 }).map((_, i) => {
  const d = new Date(now.getTime() - (29 - i) * 86400000);
  const { date, weekend } = vietnamCalendarDay(d);
  const base = weekend ? 38 : 22;
  return {
    date,
    sessions: base + ((i * 7) % 11),
    incidents: (i * 3) % 4,
    tableUsage: Math.min(96, (weekend ? 74 : 52) + ((i * 5) % 18)),
    avgMinutes: 48 + ((i * 4) % 22),
  };
});

export const seedSettings: StoreSettings = {
  storeName: "BoardGame Cafe Nhà Gỗ",
  branch: "Chi nhánh Quận 1",
  branches: [
    { id: "b1", name: "Chi nhánh Quận 1", address: "24 Lê Thánh Tôn, Quận 1, TP.HCM", tables: 8 },
    { id: "b2", name: "Chi nhánh Thảo Điền", address: "12 Xuân Thủy, TP. Thủ Đức", tables: 6 },
  ],
  address: "24 Lê Thánh Tôn, Quận 1, TP.HCM",
  hotline: "0909 123 456",
  openHours: "09:00 - 23:00 hằng ngày",
  notifyMissing: true,
  notifySupport: true,
  notifyDailyReport: false,
  compactMode: false,
};
