import type {
  ActivityItem,
  AppNotification,
  Game,
  PlayTable,
  ReportDay,
  Staff,
  StoreSettings,
  Transaction,
} from "./types";

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60000).toISOString();

const comp = (name: string, qty: number, ok = true, missingQty = 0, note?: string) => ({
  id: `${name}-${qty}`.replace(/\s+/g, "-").toLowerCase(),
  name,
  qty,
  ok,
  missingQty,
  note,
});

export const GAME_CATEGORIES = [
  "Chiến thuật",
  "Gia đình",
  "Party",
  "Suy luận",
  "Sáng tạo",
  "Kinh tế",
];

export const seedGames: Game[] = [
  {
    id: "g1",
    code: "BG-001",
    name: "Catan",
    category: "Chiến thuật",
    minPlayers: 3,
    maxPlayers: 4,
    duration: 75,
    difficulty: "Trung bình",
    status: "in_use",
    location: "Kệ A - Ngăn 1",
    description:
      "Trò chơi xây dựng và trao đổi tài nguyên trên hòn đảo Catan, phù hợp nhóm bạn thích thương lượng.",
    age: 10,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: false,
    emoji: "🏝️",
    tone: 1,
    components: [
      comp("Ô địa hình", 19),
      comp("Mảnh khung biển", 6),
      comp("Thẻ số", 18),
      comp("Thẻ tài nguyên", 95),
      comp("Thẻ phát triển", 25),
      comp("Quân cờ 4 màu", 4),
      comp("Xúc xắc", 2),
      comp("Quân cướp", 1),
    ],
    history: [
      { id: "h1", type: "deliver", label: "Giao cho Bàn 03", staff: "Trần Minh Khoa", at: iso(48) },
      { id: "h2", type: "return", label: "Nhận lại từ Bàn 07", staff: "Lê Thu Hà", at: iso(300) },
    ],
    incidents: [],
    notes: "Hộp đựng thẻ đã được thay mới tháng trước.",
    usage30d: 42,
  },
  {
    id: "g2",
    code: "BG-002",
    name: "Ticket to Ride",
    category: "Gia đình",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 60,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 2",
    description: "Nối các tuyến đường sắt xuyên quốc gia, luật đơn giản và dễ hướng dẫn cho khách mới.",
    age: 8,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🚂",
    tone: 2,
    components: [
      comp("Bàn cờ", 1),
      comp("Toa tàu nhựa", 240),
      comp("Thẻ toa tàu", 110),
      comp("Thẻ tuyến đường", 30),
      comp("Bảng điểm", 5),
    ],
    history: [{ id: "h3", type: "return", label: "Nhận lại từ Bàn 02", staff: "Lê Thu Hà", at: iso(180) }],
    incidents: [],
    notes: "",
    usage30d: 51,
  },
  {
    id: "g3",
    code: "BG-003",
    name: "Uno",
    category: "Party",
    minPlayers: 2,
    maxPlayers: 10,
    duration: 20,
    difficulty: "Dễ",
    status: "available",
    location: "Kệ B - Ngăn 1",
    description: "Game bài nhanh gọn, phù hợp nhóm đông và khách chờ bàn.",
    age: 6,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🃏",
    tone: 5,
    components: [comp("Bộ bài", 112), comp("Hướng dẫn", 1)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 88,
  },
  {
    id: "g4",
    code: "BG-004",
    name: "Exploding Kittens",
    category: "Party",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 15,
    difficulty: "Dễ",
    status: "pending_check",
    location: "Kệ B - Ngăn 2",
    description: "Game bài hài hước, vòng chơi ngắn, dễ tạo không khí sôi động.",
    age: 7,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🐱",
    tone: 3,
    components: [comp("Thẻ bài", 56), comp("Hộp đựng", 1), comp("Hướng dẫn", 1)],
    history: [{ id: "h4", type: "return", label: "Nhận lại từ Bàn 05", staff: "Phạm Gia Bảo", at: iso(25) }],
    incidents: [],
    notes: "Cần kiểm tra lại số lượng thẻ sau ca tối.",
    usage30d: 73,
  },
  {
    id: "g5",
    code: "BG-005",
    name: "Dixit",
    category: "Sáng tạo",
    minPlayers: 3,
    maxPlayers: 6,
    duration: 30,
    difficulty: "Dễ",
    status: "missing_parts",
    location: "Kệ C - Ngăn 1",
    description: "Game kể chuyện bằng tranh minh họa, nhẹ nhàng và phù hợp nhóm bạn hoặc cặp đôi.",
    age: 8,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🎨",
    tone: 4,
    components: [
      comp("Thẻ tranh", 84, false, 3, "Thiếu 3 thẻ sau ca chiều"),
      comp("Thỏ gỗ", 12),
      comp("Thẻ bình chọn", 36),
      comp("Bàn điểm", 1),
    ],
    history: [],
    incidents: [
      {
        id: "i1",
        level: "medium",
        title: "Thiếu 3 thẻ tranh",
        at: iso(200),
        staff: "Phạm Gia Bảo",
        resolved: false,
      },
    ],
    notes: "Đã liên hệ nhà cung cấp để bổ sung thẻ.",
    usage30d: 34,
  },
  {
    id: "g6",
    code: "BG-006",
    name: "Splendor",
    category: "Kinh tế",
    minPlayers: 2,
    maxPlayers: 4,
    duration: 40,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 3",
    description: "Thu thập đá quý và phát triển thương hội, luật gọn nhưng có chiều sâu chiến thuật.",
    age: 10,
    interaction: "Thấp",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "💎",
    tone: 2,
    components: [comp("Chip đá quý", 40), comp("Thẻ phát triển", 90), comp("Thẻ quý tộc", 10)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 46,
  },
  {
    id: "g7",
    code: "BG-007",
    name: "Codenames",
    category: "Suy luận",
    minPlayers: 4,
    maxPlayers: 8,
    duration: 25,
    difficulty: "Dễ",
    status: "in_use",
    location: "Kệ C - Ngăn 2",
    description: "Game đoán từ theo đội, rất hợp nhóm đông và các buổi team building.",
    age: 12,
    interaction: "Cao",
    mode: "Hợp tác",
    beginnerFriendly: true,
    emoji: "🕵️",
    tone: 3,
    components: [comp("Thẻ từ khóa", 200), comp("Thẻ điệp viên", 40), comp("Khung gợi ý", 1)],
    history: [{ id: "h5", type: "deliver", label: "Giao cho Bàn 06", staff: "Nguyễn Hải Yến", at: iso(35) }],
    incidents: [],
    notes: "",
    usage30d: 64,
  },
  {
    id: "g8",
    code: "BG-008",
    name: "Avalon",
    category: "Suy luận",
    minPlayers: 5,
    maxPlayers: 10,
    duration: 45,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ C - Ngăn 3",
    description: "Game tìm nội gián theo phe, tạo nhiều tình huống tranh luận thú vị.",
    age: 12,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: false,
    emoji: "🛡️",
    tone: 1,
    components: [comp("Thẻ nhân vật", 14), comp("Thẻ nhiệm vụ", 10), comp("Bảng nhiệm vụ", 1)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 39,
  },
  {
    id: "g9",
    code: "BG-009",
    name: "Monopoly",
    category: "Kinh tế",
    minPlayers: 2,
    maxPlayers: 6,
    duration: 120,
    difficulty: "Trung bình",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game mua bán bất động sản kinh điển, thời lượng dài phù hợp nhóm chơi thong thả.",
    age: 8,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🏘️",
    tone: 4,
    components: [
      comp("Bàn cờ", 1, false, 0, "Bản lề gấp bị rách"),
      comp("Tiền giấy", 200),
      comp("Thẻ tài sản", 28),
      comp("Quân cờ", 8),
      comp("Xúc xắc", 2),
    ],
    history: [],
    incidents: [
      { id: "i2", level: "high", title: "Bàn cờ rách bản lề", at: iso(1500), staff: "Đỗ Quang Huy", resolved: false },
    ],
    notes: "Đang chờ ép lại bản lề bàn cờ.",
    usage30d: 12,
  },
  {
    id: "g10",
    code: "BG-010",
    name: "Coup",
    category: "Suy luận",
    minPlayers: 2,
    maxPlayers: 6,
    duration: 20,
    difficulty: "Dễ",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game bluff ngắn, luật đơn giản và dễ chơi nhiều ván liên tiếp.",
    age: 10,
    interaction: "Cao",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🎭",
    tone: 5,
    components: [comp("Thẻ nhân vật", 15), comp("Đồng xu", 50)],
    history: [],
    incidents: [
      { id: "i3", level: "low", title: "Thẻ nhân vật cong góc", at: iso(900), staff: "Lê Thu Hà", resolved: false },
    ],
    notes: "",
    usage30d: 55,
  },
  {
    id: "g11",
    code: "BG-011",
    name: "Azul",
    category: "Chiến thuật",
    minPlayers: 2,
    maxPlayers: 4,
    duration: 40,
    difficulty: "Trung bình",
    status: "available",
    location: "Kệ A - Ngăn 4",
    description: "Xếp gạch men theo mẫu, thành phần đẹp mắt và rất được khách nữ yêu thích.",
    age: 8,
    interaction: "Thấp",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🧩",
    tone: 2,
    components: [comp("Viên gạch men", 100), comp("Bảng cá nhân", 4), comp("Đĩa nhà máy", 9)],
    history: [],
    incidents: [],
    notes: "",
    usage30d: 47,
  },
  {
    id: "g12",
    code: "BG-012",
    name: "Sushi Go",
    category: "Gia đình",
    minPlayers: 2,
    maxPlayers: 5,
    duration: 20,
    difficulty: "Dễ",
    status: "maintenance",
    location: "Kho bảo trì",
    description: "Game bài chọn và chuyền bài, vòng chơi ngắn và dễ tiếp cận cho trẻ em.",
    age: 6,
    interaction: "Vừa",
    mode: "Cạnh tranh",
    beginnerFriendly: true,
    emoji: "🍣",
    tone: 3,
    components: [comp("Thẻ món ăn", 108, false, 2, "Thiếu 2 thẻ sashimi"), comp("Hộp thiếc", 1)],
    history: [],
    incidents: [
      { id: "i4", level: "medium", title: "Thiếu 2 thẻ sashimi", at: iso(2400), staff: "Nguyễn Hải Yến", resolved: false },
    ],
    notes: "",
    usage30d: 29,
  },
];

export const seedTables: PlayTable[] = [
  { id: "t1", name: "Bàn 01", seats: 4, guests: 0, status: "empty" },
  { id: "t2", name: "Bàn 02", seats: 4, guests: 3, status: "playing", gameId: "g1", startedAt: iso(48), staffId: "s3" },
  { id: "t3", name: "Bàn 03", seats: 6, guests: 5, status: "playing", gameId: "g7", startedAt: iso(35), staffId: "s4" },
  { id: "t4", name: "Bàn 04", seats: 2, guests: 0, status: "cleaning" },
  { id: "t5", name: "Bàn 05", seats: 6, guests: 6, status: "support", gameId: undefined, startedAt: iso(70), staffId: "s3" },
  { id: "t6", name: "Bàn 06", seats: 4, guests: 0, status: "empty" },
  { id: "t7", name: "Bàn 07", seats: 8, guests: 7, status: "issue", startedAt: iso(120), staffId: "s5" },
  { id: "t8", name: "Bàn 08", seats: 4, guests: 0, status: "empty" },
];

export const seedStaff: Staff[] = [
  {
    id: "s1",
    name: "Nguyễn Anh Tuấn",
    email: "owner@boardgameos.vn",
    role: "Chủ quán",
    shift: "Toàn thời gian",
    active: true,
    locked: false,
    actionsToday: 12,
    lastActive: iso(6),
    permissions: ["Toàn quyền"],
  },
  {
    id: "s2",
    name: "Trần Minh Khoa",
    email: "khoa@boardgameos.vn",
    role: "Quản lý",
    shift: "Ca sáng (08:00 - 16:00)",
    active: true,
    locked: false,
    actionsToday: 27,
    lastActive: iso(14),
    permissions: ["Kho game", "Bàn chơi", "Báo cáo", "Nhân viên"],
  },
  {
    id: "s3",
    name: "Lê Thu Hà",
    email: "staff@boardgameos.vn",
    role: "Nhân viên phục vụ",
    shift: "Ca chiều (14:00 - 22:00)",
    active: true,
    locked: false,
    actionsToday: 34,
    lastActive: iso(3),
    permissions: ["Giao nhận game", "Bàn chơi", "Kiểm tra linh kiện"],
  },
  {
    id: "s4",
    name: "Nguyễn Hải Yến",
    email: "yen@boardgameos.vn",
    role: "Thu ngân",
    shift: "Ca chiều (14:00 - 22:00)",
    active: true,
    locked: false,
    actionsToday: 18,
    lastActive: iso(22),
    permissions: ["Bàn chơi", "Tư vấn game"],
  },
  {
    id: "s5",
    name: "Phạm Gia Bảo",
    email: "bao@boardgameos.vn",
    role: "Nhân viên kho",
    shift: "Ca tối (17:00 - 23:00)",
    active: true,
    locked: false,
    actionsToday: 21,
    lastActive: iso(41),
    permissions: ["Kho game", "Kiểm tra linh kiện"],
  },
  {
    id: "s6",
    name: "Đỗ Quang Huy",
    email: "huy@boardgameos.vn",
    role: "Nhân viên phục vụ",
    shift: "Ca sáng (08:00 - 16:00)",
    active: false,
    locked: true,
    actionsToday: 0,
    lastActive: iso(1600),
    permissions: ["Giao nhận game"],
  },
];

export const seedTransactions: Transaction[] = [
  { id: "tx1", type: "deliver", gameId: "g7", tableId: "t3", staffId: "s4", at: iso(35) },
  { id: "tx2", type: "deliver", gameId: "g1", tableId: "t2", staffId: "s3", at: iso(48) },
  { id: "tx3", type: "return", gameId: "g4", tableId: "t5", staffId: "s5", at: iso(25), note: "Chờ kiểm tra linh kiện" },
  { id: "tx4", type: "return", gameId: "g2", tableId: "t1", staffId: "s3", at: iso(180) },
  { id: "tx5", type: "deliver", gameId: "g3", tableId: "t6", staffId: "s3", at: iso(220) },
  { id: "tx6", type: "return", gameId: "g3", tableId: "t6", staffId: "s3", at: iso(260) },
  { id: "tx7", type: "deliver", gameId: "g5", tableId: "t7", staffId: "s5", at: iso(320) },
  { id: "tx8", type: "return", gameId: "g5", tableId: "t7", staffId: "s5", at: iso(360), note: "Thiếu 3 thẻ tranh" },
  { id: "tx9", type: "deliver", gameId: "g11", tableId: "t4", staffId: "s2", at: iso(420) },
  { id: "tx10", type: "return", gameId: "g11", tableId: "t4", staffId: "s2", at: iso(470) },
];

export const seedActivities: ActivityItem[] = [
  { id: "a1", kind: "deliver", text: "Giao Codenames cho Bàn 03", at: iso(35), staff: "Nguyễn Hải Yến" },
  { id: "a2", kind: "deliver", text: "Giao Catan cho Bàn 02", at: iso(48), staff: "Lê Thu Hà" },
  { id: "a3", kind: "return", text: "Nhận lại Exploding Kittens từ Bàn 05", at: iso(25), staff: "Phạm Gia Bảo" },
  { id: "a4", kind: "missing", text: "Báo thiếu 3 thẻ tranh của Dixit", at: iso(200), staff: "Phạm Gia Bảo" },
  { id: "a5", kind: "maintenance", text: "Chuyển Monopoly sang bảo trì", at: iso(1500), staff: "Đỗ Quang Huy" },
  { id: "a6", kind: "table", text: "Bàn 07 báo cần hỗ trợ", at: iso(18), staff: "Phạm Gia Bảo" },
  { id: "a7", kind: "checklist", text: "Hoàn tất checklist Ticket to Ride", at: iso(180), staff: "Lê Thu Hà" },
  { id: "a8", kind: "return", text: "Nhận lại Ticket to Ride từ Bàn 02", at: iso(180), staff: "Lê Thu Hà" },
  { id: "a9", kind: "table", text: "Bàn 04 chuyển sang trạng thái đang dọn", at: iso(90), staff: "Nguyễn Hải Yến" },
  { id: "a10", kind: "deliver", text: "Giao Uno cho Bàn 06", at: iso(220), staff: "Lê Thu Hà" },
  { id: "a11", kind: "return", text: "Nhận lại Uno từ Bàn 06", at: iso(260), staff: "Lê Thu Hà" },
  { id: "a12", kind: "checklist", text: "Hoàn tất checklist Uno", at: iso(258), staff: "Lê Thu Hà" },
  { id: "a13", kind: "maintenance", text: "Chuyển Coup sang bảo trì", at: iso(900), staff: "Lê Thu Hà" },
  { id: "a14", kind: "missing", text: "Báo thiếu 2 thẻ Sushi Go", at: iso(2400), staff: "Nguyễn Hải Yến" },
  { id: "a15", kind: "deliver", text: "Giao Azul cho Bàn 04", at: iso(420), staff: "Trần Minh Khoa" },
  { id: "a16", kind: "return", text: "Nhận lại Azul từ Bàn 04", at: iso(470), staff: "Trần Minh Khoa" },
  { id: "a17", kind: "table", text: "Mở phiên chơi mới tại Bàn 03", at: iso(36), staff: "Nguyễn Hải Yến" },
  { id: "a18", kind: "checklist", text: "Hoàn tất checklist Splendor", at: iso(600), staff: "Phạm Gia Bảo" },
  { id: "a19", kind: "deliver", text: "Giao Dixit cho Bàn 07", at: iso(320), staff: "Phạm Gia Bảo" },
  { id: "a20", kind: "return", text: "Nhận lại Dixit từ Bàn 07", at: iso(360), staff: "Phạm Gia Bảo" },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "n1",
    type: "Kiểm tra",
    level: "warning",
    title: "Exploding Kittens chưa được kiểm tra",
    body: "Game đã trả về từ Bàn 05 nhưng chưa hoàn tất checklist linh kiện.",
    at: iso(25),
    read: false,
    resolved: false,
    to: "/app/checklist",
  },
  {
    id: "n2",
    type: "Linh kiện",
    level: "critical",
    title: "Dixit thiếu 3 thẻ tranh",
    body: "Nhân viên Phạm Gia Bảo đã báo thiếu linh kiện trong ca chiều.",
    at: iso(200),
    read: false,
    resolved: false,
    to: "/app/games/g5",
  },
  {
    id: "n3",
    type: "Hỗ trợ",
    level: "warning",
    title: "Bàn 07 yêu cầu hỗ trợ",
    body: "Khách cần nhân viên hướng dẫn luật chơi.",
    at: iso(18),
    read: false,
    resolved: false,
    to: "/app/tables",
  },
  {
    id: "n4",
    type: "Bảo trì",
    level: "warning",
    title: "Monopoly đang chờ bảo trì",
    body: "Bàn cờ bị rách bản lề, cần xử lý trước cuối tuần.",
    at: iso(1500),
    read: true,
    resolved: false,
    to: "/app/games/g9",
  },
  {
    id: "n5",
    type: "Checklist",
    level: "info",
    title: "Lê Thu Hà hoàn tất checklist Ticket to Ride",
    body: "Đầy đủ linh kiện, game đã về kho.",
    at: iso(180),
    read: true,
    resolved: true,
    to: "/app/games/g2",
  },
  {
    id: "n6",
    type: "Tài khoản",
    level: "info",
    title: "Tài khoản Đỗ Quang Huy đã bị khóa",
    body: "Tài khoản tạm khóa do nghỉ ca dài ngày.",
    at: iso(1600),
    read: true,
    resolved: true,
    to: "/app/staff",
  },
];

export const seedReports: ReportDay[] = Array.from({ length: 30 }).map((_, i) => {
  const d = new Date(now.getTime() - (29 - i) * 86400000);
  const weekend = d.getDay() === 0 || d.getDay() === 6;
  const base = weekend ? 38 : 22;
  return {
    date: d.toISOString().slice(0, 10),
    sessions: base + ((i * 7) % 11),
    incidents: (i * 3) % 4,
    tableUsage: Math.min(96, (weekend ? 74 : 52) + ((i * 5) % 18)),
    avgMinutes: 48 + ((i * 4) % 22),
  };
});

export const seedSettings: StoreSettings = {
  storeName: "BoardGame Cafe Nhà Gỗ",
  branch: "Chi nhánh Quận 1",
  branches: [
    { id: "b1", name: "Chi nhánh Quận 1", address: "24 Lê Thánh Tôn, Quận 1, TP.HCM", tables: 8 },
    { id: "b2", name: "Chi nhánh Thảo Điền", address: "12 Xuân Thủy, TP. Thủ Đức", tables: 6 },
  ],
  address: "24 Lê Thánh Tôn, Quận 1, TP.HCM",
  hotline: "0909 123 456",
  openHours: "09:00 - 23:00 hằng ngày",
  notifyMissing: true,
  notifySupport: true,
  notifyDailyReport: false,
  compactMode: false,
};
