/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as AppChecklistRouteImport } from './routes/app.checklist'
import { Route as AppHandoverRouteImport } from './routes/app.handover'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppTablesRouteImport } from './routes/app.tables'
import { Route as AppGamesIndexRouteImport } from './routes/app.games.index'
import { Route as AppGamesGameIdRouteImport } from './routes/app.games.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoverRoute = AppHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameIdRoute = AppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/checklist': typeof AppChecklistRoute
  '/app/handover': typeof AppHandoverRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tables': typeof AppTablesRoute
  '/app/': typeof AppIndexRoute
  '/app/games/$gameId': typeof AppGamesGameIdRoute
  '/app/games/': typeof AppGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/checklist': typeof AppChecklistRoute
  '/app/handover': typeof AppHandoverRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tables': typeof AppTablesRoute
  '/app': typeof AppIndexRoute
  '/app/games/$gameId': typeof AppGamesGameIdRoute
  '/app/games': typeof AppGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/checklist': typeof AppChecklistRoute
  '/app/handover': typeof AppHandoverRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/tables': typeof AppTablesRoute
  '/app/': typeof AppIndexRoute
  '/app/games/$gameId': typeof AppGamesGameIdRoute
  '/app/games/': typeof AppGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/advisor'
    | '/app/checklist'
    | '/app/handover'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/tables'
    | '/app/'
    | '/app/games/$gameId'
    | '/app/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/advisor'
    | '/app/checklist'
    | '/app/handover'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/tables'
    | '/app'
    | '/app/games/$gameId'
    | '/app/games'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/advisor'
    | '/app/checklist'
    | '/app/handover'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/tables'
    | '/app/'
    | '/app/games/$gameId'
    | '/app/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklist': {
      id: '/app/checklist'
      path: '/checklist'
      fullPath: '/app/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/handover': {
      id: '/app/handover'
      path: '/handover'
      fullPath: '/app/handover'
      preLoaderRoute: typeof AppHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tables': {
      id: '/app/tables'
      path: '/tables'
      fullPath: '/app/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/': {
      id: '/app/games/'
      path: '/games'
      fullPath: '/app/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/$gameId': {
      id: '/app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/app/games/$gameId'
      preLoaderRoute: typeof AppGamesGameIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppChecklistRoute: typeof AppChecklistRoute
  AppHandoverRoute: typeof AppHandoverRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTablesRoute: typeof AppTablesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppChecklistRoute: AppChecklistRoute,
  AppHandoverRoute: AppHandoverRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTablesRoute: AppTablesRoute,
  AppIndexRoute: AppIndexRoute,
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
